version: "3.8"

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - url-service

  url-service:
    build: ./services/url-service
    ports:
      - "8001:8000"
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: url-shortener-cache
    ports:
      - "6379:6379"

volumes:
  db_data:
